feature_store_params:
  table_name: 'churn_features'
  primary_keys: 'customerID'
  # If feature_names not provided, will use all features in the feature table (excluding primary keys and label_col)
#  feature_names: ['gender', 'seniorCitizen', 'partner', 'dependents', 'tenure',
#                  'phoneService', 'multipleLines', 'internetService', 'onlineSecurity',
#                  'onlineBackup', 'deviceProtection', 'techSupport', 'streamingTV',
#                  'streamingMovies', 'contract', 'paperlessBilling', 'paymentMethod',
#                  'monthlyCharges', 'totalCharges']

mlflow_params:
  experiment_path:
  run_name:

model_params:
  learning_rate: 0.008098213761399603
  max_depth: 8
  min_child_weight': 3
  subsample: 0.12038118521316003
  random_state: 42