custom:

  # Cluster configs for each environment
  # For demo purposes we will use a warm pool to acquire instances from
  default-cluster-spec: &default-cluster-spec
    spark_version: '11.0.x-cpu-ml-scala2.12'
#    node_type_id: 'i3.xlarge' # node_type_id and driver_node_type_id cannot be supplied when an instance 'pool ID is provided
#    driver_node_type_id: 'i3.xlarge'
    num_workers: 1
    driver_instance_pool_id: '0617-151415-bells2-pool-hh7h6tjm'
    instance_pool_id: '0617-151415-bells2-pool-hh7h6tjm'

  dev-cluster-config: &dev-cluster-config
    new_cluster:
      <<: *default-cluster-spec

  staging-cluster-config: &staging-cluster-config
    new_cluster:
      <<: *default-cluster-spec

  prod-cluster-config: &prod-cluster-config
    new_cluster:
      <<: *default-cluster-spec

# Databricks Jobs definitions
# please note that we're using FUSE reference for config, and env files, hence we're going to load this file using its local FS path
environments:

  dev:
    strict_path_adjustment_policy: true
    jobs:
      - name: 'demo-setup'
        <<: *dev-cluster-config
        spark_python_task:
          python_file: 'file://telco_churn/jobs/demo_setup_job.py'
          parameters: ['--base-data-params', 'file:fuse://conf/.base_data_params.env',
                       '--env', 'file:fuse://conf/.dev.env',
                       '--conf-file', 'file:fuse://conf/job_configs/demo_setup.yml']
      - name: 'feature-table-creation'
        <<: *dev-cluster-config
        spark_python_task:
          python_file: 'file://telco_churn/jobs/feature_table_creator_job.py'
          parameters: ['--base-data-params', 'file:fuse://conf/.base_data_params.env',
                       '--env', 'file:fuse://conf/.dev.env',
                       '--conf-file', 'file:fuse://conf/job_configs/feature_table_creation.yml']
      - name: 'model-train'
        <<:
          - *dev-cluster-config
        spark_python_task:
          python_file: 'file://telco_churn/jobs/model_train_job.py'
          parameters: ['--base-data-params', 'file:fuse://conf/.base_data_params.env',
                       '--env', 'file:fuse://conf/.dev.env',
                       '--conf-file', 'file:fuse://conf/job_configs/model_train.yml']
      - name: 'model-deployment'
        <<:
          - *dev-cluster-config
        spark_python_task:
          python_file: 'file://telco_churn/jobs/model_deployment_job.py'
          parameters: ['--base-data-params', 'file:fuse://conf/.base_data_params.env',
                       '--env', 'file:fuse://conf/.dev.env',
                       '--conf-file', 'file:fuse://conf/job_configs/model_deployment.yml']
      - name: 'model-inference-batch'
        <<:
          - *dev-cluster-config
        spark_python_task:
          python_file: 'file://telco_churn/jobs/model_inference_job.py'
          parameters: ['--base-data-params', 'file:fuse://conf/.base_data_params.env',
                       '--env', 'file:fuse://conf/.dev.env',
                       '--conf-file', 'file:fuse://conf/job_configs/model_inference_batch.yml']
      - name: 'sample-integration-test'
        <<:
          - *dev-cluster-config
        spark_python_task:
          python_file: 'file://tests/integration/sample_test.py'
          parameters: ['--base-data-params', 'file:fuse://conf/.base_data_params.env',
                       '--env', 'file:fuse://conf/.dev.env',
                       '--conf-file', 'file:fuse://conf/job_configs/sample_test.yml' ]

  staging:
    strict_path_adjustment_policy: true
    jobs:
      - name: 'sample-integration-test'
        <<:
          - *staging-cluster-config
        spark_python_task:
          python_file: 'file://tests/integration/sample_test.py'
          parameters: ['--env', 'file:fuse://conf/.staging.env',
                       '--conf-file', 'file:fuse://conf/job_configs/sample_test.yml' ]

  prod:
    strict_path_adjustment_policy: true
    jobs:
      - name: 'demo-setup'
        <<: *prod-cluster-config
        spark_python_task:
          python_file: 'file://telco_churn/jobs/demo_setup_job.py'
          parameters: ['--base-data-params', 'file:fuse://conf/.base_data_params.env',
                       '--env', 'file:fuse://conf/.prod.env',
                       '--conf-file', 'file:fuse://conf/job_configs/demo_setup.yml' ]
      - name: 'initial-model-train-register'
        tasks:
          - task_key: 'demo-setup'
            <<:
              - *prod-cluster-config
            spark_python_task:
              python_file: 'file://telco_churn/jobs/demo_setup_job.py'
              parameters: ['--base-data-params', 'file:fuse://conf/.base_data_params.env',
                           '--env', 'file:fuse://conf/.prod.env',
                           '--conf-file', 'file:fuse://conf/job_configs/demo_setup.yml' ]
          - task_key: 'feature-table-creation'
            <<: *prod-cluster-config
            depends_on:
              - task_key: 'demo-setup'
            spark_python_task:
              python_file: 'file://telco_churn/jobs/feature_table_creator_job.py'
              parameters: ['--base-data-params', 'file:fuse://conf/.base_data_params.env',
                           '--env', 'file:fuse://conf/.prod.env',
                           '--conf-file', 'file:fuse://conf/job_configs/feature_table_creation.yml']
          - task_key: 'model-train'
            <<: *prod-cluster-config
            depends_on:
              - task_key: 'demo-setup'
              - task_key: 'feature-table-creation'
            spark_python_task:
              python_file: 'file://telco_churn/jobs/model_train_job.py'
              parameters: ['--base-data-params', 'file:fuse://conf/.base_data_params.env',
                           '--env', 'file:fuse://conf/.prod.env',
                           '--conf-file', 'file:fuse://conf/job_configs/model_train.yml']
      - name: 'model-train'
        <<:
          - *prod-cluster-config
        spark_python_task:
          python_file: 'file://telco_churn/jobs/model_train_job.py'
          parameters: ['--base-data-params', 'file:fuse://conf/.base_data_params.env',
                       '--env', 'file:fuse://conf/.prod.env',
                       '--conf-file', 'file:fuse://conf/job_configs/model_train.yml']
      - name: 'model-deployment'
        <<:
          - *prod-cluster-config
        spark_python_task:
          python_file: 'file://telco_churn/jobs/model_deployment_job.py'
          parameters: ['--base-data-params', 'file:fuse://conf/.base_data_params.env',
                       '--env', 'file:fuse://conf/.prod.env',
                       '--conf-file', 'file:fuse://conf/job_configs/model_deployment.yml']
      - name: 'model-inference-batch'
        <<:
          - *prod-cluster-config
        spark_python_task:
          python_file: 'file://telco_churn/jobs/model_inference_job.py'
          parameters: ['--base-data-params', 'file:fuse://conf/.base_data_params.env',
                       '--env', 'file:fuse://conf/.prod.env',
                       '--conf-file', 'file:fuse://conf/job_configs/model_inference_batch.yml']